<?php
namespace App\Game; use App\DB; use RuntimeException;
final class BusinessService { public const CATEGORIES=['coffee'=>['emoji'=>'☕','name'=>'کافه','cost'=>15000,'base_rev'=>400,'min_level'=>3],'rest'=>['emoji'=>'🍽','name'=>'رستوران','cost'=>60000,'base_rev'=>1400,'min_level'=>5],'store'=>['emoji'=>'🛒','name'=>'فروشگاه آنلاین','cost'=>30000,'base_rev'=>800,'min_level'=>4],'startup'=>['emoji'=>'🚀','name'=>'استارتاپ تکنولوژی','cost'=>150000,'base_rev'=>3500,'min_level'=>8],'gaming'=>['emoji'=>'🎮','name'=>'شرکت گیمینگ','cost'=>250000,'base_rev'=>5500,'min_level'=>10],'media'=>['emoji'=>'📺','name'=>'شرکت رسانه‌ای','cost'=>400000,'base_rev'=>8500,'min_level'=>12]];
 public static function getMyBusiness(int $id):?array{$s=DB::pdo()->prepare('SELECT * FROM businesses WHERE owner_id=? LIMIT 1');$s->execute([$id]);return $s->fetch()?:null;}
 public static function create(array $u,string $cat,string $name):void{$c=self::CATEGORIES[$cat]??throw new RuntimeException('bad_cat');$name=trim($name);if((int)$u['level']<$c['min_level'])throw new RuntimeException('level_low');if(mb_strlen($name)<2||mb_strlen($name)>25)throw new RuntimeException('bad_name');if(self::getMyBusiness((int)$u['id']))throw new RuntimeException('already_own');EconomyService::spend($u,$c['cost'],'تأسیس کسب‌وکار: '.$name);DB::pdo()->prepare('INSERT INTO businesses (owner_id,name,category,last_income_ts,created_at) VALUES (?,?,?,?,?)')->execute([$u['id'],$name,$cat,time(),time()]);PlayerService::update((int)$u['id'],['business_id'=>(int)DB::pdo()->lastInsertId()]);AchievementService::check($u,'first_business');}
 public static function collectIncome(array $u,array $b):array{$now=time();$elapsed=max(0,$now-(int)$b['last_income_ts']);$cycles=intdiv($elapsed,28800);if($cycles<1)return['amount'=>0,'wait'=>28800-$elapsed];$c=self::CATEGORIES[$b['category']];$per=(int)round($c['base_rev']*(int)$b['level']*(0.8+(int)$b['reputation']/250));$amount=$per*$cycles;$next=(int)$b['last_income_ts']+$cycles*28800;DB::pdo()->prepare('UPDATE businesses SET last_income_ts=? WHERE id=?')->execute([$next,$b['id']]);EconomyService::earn($u,$amount,'درآمد کسب‌وکار: '.$b['name']);return['amount'=>$amount,'wait'=>0];}
 public static function upgrade(array $u,array $b):int{$cost=self::CATEGORIES[$b['category']]['base_rev']*(int)$b['level']*20;EconomyService::spend($u,$cost,'ارتقای کسب‌وکار');DB::pdo()->prepare('UPDATE businesses SET level=level+1,reputation=MIN(100,reputation+5) WHERE id=?')->execute([$b['id']]);MissionService::progress($u,'biz_upgrades',1);return $cost;}
 public static function advertise(array $u,array $b):int{$cost=2000*(int)$b['level'];EconomyService::spend($u,$cost,'تبلیغات کسب‌وکار');DB::pdo()->prepare('UPDATE businesses SET reputation=MIN(100,reputation+10) WHERE id=?')->execute([$b['id']]);return $cost;}
 public static function sell(array $u,array $b):int{$c=self::CATEGORIES[$b['category']];$v=(int)round($c['cost']*(int)$b['level']*(0.5+(int)$b['reputation']/200));DB::pdo()->prepare('DELETE FROM businesses WHERE id=? AND owner_id=?')->execute([$b['id'],$u['id']]);PlayerService::update((int)$u['id'],['business_id'=>null]);EconomyService::earn($u,$v,'فروش کسب‌وکار: '.$b['name']);return $v;}}
