<?php
namespace App\Game;
use App\DB; use RuntimeException;
final class EconomyService {
 public static function spend(array $user,int $amount,string $note,bool $fromBank=false): void { if($amount<=0) throw new RuntimeException('مقدار نامعتبر'); $col=$fromBank?'bank':'cash'; $pdo=DB::pdo(); $pdo->beginTransaction(); try{$st=$pdo->prepare("UPDATE users SET $col = $col - ?, updated_at=? WHERE id=? AND $col>=?");$st->execute([$amount,time(),$user['id'],$amount]);if(!$st->rowCount()) throw new RuntimeException('not_enough_money');self::log((int)$user['id'],'spend',$amount,$note);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
 public static function earn(array $user,int $amount,string $note): void {if($amount<=0)return;$pdo=DB::pdo();$pdo->beginTransaction();try{$pdo->prepare('UPDATE users SET cash=cash+?, updated_at=? WHERE id=?')->execute([$amount,time(),$user['id']]);self::log((int)$user['id'],'earn',$amount,$note);$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
 public static function transfer(array $from,int $toUserId,int $amount): void {if($amount<=0||$amount>1000000)throw new RuntimeException('مقدار نامعتبر');if((int)$from['id']===$toUserId)throw new RuntimeException('به خودت نمیشه! 😅');$pdo=DB::pdo();$pdo->beginTransaction();try{$st=$pdo->prepare('UPDATE users SET cash=cash-?, updated_at=? WHERE id=? AND cash>=?');$st->execute([$amount,time(),$from['id'],$amount]);if(!$st->rowCount())throw new RuntimeException('not_enough_money');$st=$pdo->prepare('UPDATE users SET cash=cash+?, updated_at=? WHERE id=?');$st->execute([$amount,time(),$toUserId]);if(!$st->rowCount())throw new RuntimeException('کاربر مقصد پیدا نشد');self::log((int)$from['id'],'transfer_out',$amount,"به کاربر #$toUserId");self::log($toUserId,'transfer_in',$amount,'انتقال دریافتی');$pdo->commit();}catch(\Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
 public static function log(int $userId,string $type,int $amount,string $note): void {DB::pdo()->prepare('INSERT INTO transactions (user_id,type,amount,note,created_at) VALUES (?,?,?,?,?)')->execute([$userId,$type,$amount,$note,time()]);}
}
