<?php
namespace App\Game;
use App\DB;
final class PlayerService { public const BACKGROUNDS=['normal'=>['emoji'=>'🟢','label'=>'خانواده معمولی','cash'=>500,'xp_mult'=>1.0],'poor'=>['emoji'=>'🔴','label'=>'خانواده فقیر','cash'=>100,'xp_mult'=>1.3],'rich'=>['emoji'=>'🟡','label'=>'خانواده ثروتمند','cash'=>5000,'xp_mult'=>0.8],'mystery'=>['emoji'=>'🟣','label'=>'گذشته مرموز','cash'=>750,'xp_mult'=>1.1],'selfmade'=>['emoji'=>'⚫','label'=>'خودساخته','cash'=>50,'xp_mult'=>1.5]]; public const XP_PER_LEVEL=1000;
 public static function findByTg(int $tgId):?array{$s=DB::pdo()->prepare('SELECT * FROM users WHERE telegram_id=?');$s->execute([$tgId]);return $s->fetch()?:null;}
 public static function create(int $tgId,?string $username,string $name,string $nick,string $bg):array{$b=self::BACKGROUNDS[$bg]??self::BACKGROUNDS['normal'];$pdo=DB::pdo();$code='SL-'.random_int(100000,999999);$now=time();$pdo->prepare('INSERT INTO users (telegram_id,username,player_code,character_name,nickname,background,cash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)')->execute([$tgId,$username,$code,$name,$nick,$bg,$b['cash'],$now,$now]);$u=self::findByTg($tgId);EconomyService::log((int)$u['id'],'initial',(int)$b['cash'],'سرمایه اولیه');return $u;}
 public static function update(int $userId,array $fields):void{if(!$fields)return;$allowed=['username','character_name','nickname','background','level','xp','cash','bank','energy','health','happiness','fame','power','influence','city','job','business_id','property','vehicle','banned','notif_enabled','state','last_energy_ts'];$fields=array_intersect_key($fields,array_flip($allowed));if(!$fields)return;$sets=[];$vals=[];foreach($fields as $k=>$v){$sets[]="$k=?";$vals[]=$v;}$sets[]='updated_at=?';$vals[]=time();$vals[]=$userId;DB::pdo()->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=?')->execute($vals);}
 public static function addXp(array $user,int $xp):string{$mult=(float)(self::BACKGROUNDS[$user['background']]['xp_mult']??1);$new=(int)$user['xp']+(int)round($xp*$mult);$level=(int)$user['level'];$up='';while($new>=self::XP_PER_LEVEL*$level){$new-=self::XP_PER_LEVEL*$level;$level++;$up="\n\n🎉 <b>لول جدید: $level</b>";}self::update((int)$user['id'],['xp'=>$new,'level'=>$level]);if($level>=(int)$user['level'])MissionService::progress($user,'level',$level);return $up;}
 public static function renderProfile(array $u):string{$e=fn($s)=>htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$job=$u['job']?:'بی‌کار';$worth=(int)$u['cash']+(int)$u['bank'];return "━━━━━━━━━━━━━━\n👤 <b>{$e($u['character_name'])}</b> ({$e($u['nickname'])})\n\n🆔 <code>{$e($u['player_code'])}</code>\n⭐ لول: {$u['level']} | XP: {$u['xp']}\n\n💵 پول نقد: ".number_format($u['cash'])." دلار\n🏦 بانک: ".number_format($u['bank'])." دلار\n📊 ارزش کل: ".number_format($worth)." دلار\n\n🔥 شهرت: {$u['fame']}\n👑 قدرت: {$u['power']}\n🌍 نفوذ: {$u['influence']}\n\n⚡ انرژی: {$u['energy']}/100\n❤️ سلامتی: {$u['health']}/100\n😊 رضایت: {$u['happiness']}/100\n\n💼 شغل: {$e($job)}\n📍 شهر: دارک سیتی\n━━━━━━━━━━━━━━";}}
